const types = {
  LOAD_DATA_STARTED: 'LOAD_DATA_STARTED',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOAD_DATA_FAILED: 'LOAD_DATA_FAILED',
  POST_DATA_STARTED: 'POST_DATA_STARTED',
  POST_DATA_SUCCESS: 'POST_DATA_SUCCESS',
  POST_DATA_FAILED: 'POST_DATA_FAILED',
  DELETE_DATA_STARTED: 'DELETE_DATA_STARTED',
  DELETE_DATA_SUCCESS: 'DELETE_DATA_SUCCESS',
  DELETE_DATA_FAILED: 'DELETE_DATA_FAILED',
  UPDATE_DATA_STARTED: 'UPDATE_DATA_STARTED',
  UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAILED: 'UPDATE_DATA_FAILED'
};

export default types;
